#!/bin/sh

# This file is meant to be copied to
# .git/hooks to re-apply permissions after a pull

# make folders executable but unreadable for others
find . \( ! -regex '\.\|.*/\..*' \) -type d -exec chmod 701 {} +
# regular files: rw access for the owner, r access for others (web access)
find . \( ! -regex '.*/\..*' \) -type f -exec chmod 604 {} +
# make this script executable to owner and group and inaccessible to others
chmod 700 post-merge
